catalog:
  '@types/node': ^22.0.0
  '@astrojs/db': ^0.15.0
  '@astrojs/node': ^9.3.0
  '@inox-tools/astro-tests': ^0.6.2
  astro: ^5.11.0
    
packages:
  - "packages/*"
  - "packages/*/test/fixtures/*"
  - "playground"
