packages:
  - packages/*
  - packages/*/test/fixtures/*
  - playground

catalog:
  '@astrojs/db': ^0.18.0
  '@astrojs/node': ^9.5.0
  '@inox-tools/astro-tests': ^0.8.0
  '@types/node': ^22.0.0
  astro: ^5.13.9

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - '@studiocms/*'
  - '@withstudiocms/*'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - oxc-resolver
  - sharp
