catalog:
  '@types/node': ^22.0.0
  '@astrojs/db': ^0.17.1
  '@astrojs/node': ^9.4.2
  '@inox-tools/astro-tests': ^0.7.0
  astro: ^5.13.2
    
packages:
  - "packages/*"
  - "packages/*/test/fixtures/*"
  - "playground"
