catalog:
  '@types/node': ^22.0.0
  '@astrojs/db': ^0.17.0
  '@astrojs/node': ^9.3.3
  '@inox-tools/astro-tests': ^0.7.0
  astro: ^5.12.8
    
packages:
  - "packages/*"
  - "packages/*/test/fixtures/*"
  - "playground"
