packages:
  - packages/*
  - packages/*/test/fixtures/*
  - playground

catalog:
  '@astrojs/db': ^0.17.1
  '@astrojs/node': ^9.4.3
  '@inox-tools/astro-tests': ^0.7.0
  '@types/node': ^22.0.0
  astro: ^5.13.3

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - oxc-resolver
  - sharp

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - '@studiocms/*'
  - '@withstudiocms/*'
