// This file is generated by Astro DB
declare module 'astro:db' {
	export const AstrojsWebVitals_Metric: import("@astrojs/db/runtime").Table<
		"AstrojsWebVitals_Metric",
		{"pathname":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"pathname","collection":"AstrojsWebVitals_Metric","primaryKey":false,"optional":false}},"route":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"route","collection":"AstrojsWebVitals_Metric","primaryKey":false,"optional":false}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"AstrojsWebVitals_Metric","primaryKey":false,"optional":false}},"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"AstrojsWebVitals_Metric","primaryKey":true}},"value":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"value","collection":"AstrojsWebVitals_Metric","primaryKey":false,"optional":false}},"rating":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"rating","collection":"AstrojsWebVitals_Metric","primaryKey":false,"optional":false}},"timestamp":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"timestamp","collection":"AstrojsWebVitals_Metric"}}}
	>;
}
