name: CI - PR Tests

on: 
  pull_request:
    paths:
        - 'packages/**'

jobs:
  release:
    name: PR tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Run Build
        run: pnpm build
  
      - name: Run Tests
        run: pnpm test
        