name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]
    paths:
      - 'packages/**'

jobs:
  renovate:
    name: Update Renovate PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@f25d784f13eb09227429cebd880ade75d19d6283 # v1.1.9
        with:
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}
          use-conventional-commits: true
          author-name: StudioCMS
          author-email: no-reply@studiocms.dev
